name: mevo
description: null
publish_to: "none"

version: 1.0.2-beta1.2.2+8

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.12.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.10
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  file_picker: ^6.1.1
  firebase_app_check: ^0.2.1+4
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_keyboard_visibility: ^5.4.1
  flutter_local_notifications: ^16.2.0
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  get: ^4.6.6
  get_it: ^7.6.4
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.18.1
  latlong2: ^0.9.0
  overlayment: ^0.2.1
  permission_handler: ^11.3.0
  pin_code_fields: ^8.0.1
  sqflite: ^2.3.0
  syncfusion_flutter_pdfviewer: ^23.1.44
  url_launcher: ^6.2.1
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/svg/
    - assets/sounds/
